variables:
  IMAGE_NAME: dispatch
  IMAGE_FILE_PATH: $CI_PROJECT_DIR

include:
  - project: christiantragesser/gitlab-ci-templates
    ref: master
    file:
      - kaniko.yml

stages:
  - publish

publish:container:
  stage: publish
  extends:
    - .kaniko
  variables:
    DOCKER_BUILD_STAGE: publish
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - go.*
        - main.go
        - dispatch/*
        - status/*
        - Dockerfile
      when: always

publish:linux:
  stage: publish
  extends:
    - .kaniko
  variables:
    DOCKER_BUILD_STAGE: linux-binary
    KANIKO_ADDITIONAL_ARGS: --destination registry.local/image:latest --no-push --ignore-path /dispatch-linux-amd64 --ignore-path /dispatch-linux-amd64.sha256
  after_script:
    - cp /dispatch-linux-amd64 $CI_PROJECT_DIR
  artifacts:
    paths:
      - dispatch-linux-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - go.*
        - main.go
        - dispatch/*
        - status/*
        - Dockerfile

publish:macos:
  stage: publish
  extends:
    - .kaniko
  variables:
    DOCKER_BUILD_STAGE: macos-binary
    KANIKO_ADDITIONAL_ARGS: --destination registry.local/image:latest --no-push --ignore-path /dispatch-darwin-amd64 --ignore-path /dispatch-darwin-amd64.sha256
  after_script:
    - cp /dispatch-darwin-amd64 $CI_PROJECT_DIR
  artifacts:
    paths:
      - dispatch-darwin-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - go.*
        - main.go
        - dispatch/*
        - status/*
        - Dockerfile