variables:
  IMAGE_NAME: dispatch

include:
  - project: christiantragesser/gitlab-ci-templates
    ref: master
    file:
      - goreleaser.yml
      - kaniko.yml

.default_branch_only:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    changes:
      - go.*
      - main.go
      - dispatch/*
      - status/*
      - tui*/*
      - pkg/Dockerfile.pipeline

stages:
  - publish
  - release

publish:binary:
  stage: publish
  extends:
    - .bin_publish
    - .default_branch_only
  artifacts:
    paths:
      - dist/${IMAGE_NAME}_linux_amd64/${IMAGE_NAME}-linux-amd64
  
publish:container:
  stage: publish
  needs: ["publish:binary"]
  extends:
    - .kaniko_publish
    - .default_branch_only
  variables:
    DOCKERFILE_PATH: ./pkg/Dockerfile.pipeline
    DOCKER_BUILD_STAGE: publish
  dependencies:
    - publish:binary

release:github:
  stage: release
  extends:
    - .gh_release

release:container:
  stage: release
  extends:
    - .kaniko_release
