image: registry.gitlab.com/christiantragesser/dind-py:3

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  SERVICE: dispatch
  EXT_NAME: $CI_REGISTRY/christiantragesser/$SERVICE

services:
  - name: docker:dind
    command: ["--registry-mirror=https://dockerhub-mirror0.artifactory.asynchrony.com"]

stages:
  - test

test:
  stage: test
  script:
    - $CI_PROJECT_DIR/ci.py test
    - docker tag local/${SERVICE}:latest $EXT_NAME:latest
    - docker tag $EXT_NAME:latest $EXT_NAME:$CI_COMMIT_SHA
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $EXT_NAME:latest | grep -e "The push refers to" -e latest
    - docker push $EXT_NAME:$CI_COMMIT_SHA | grep -e "The push refers to" -e latest